/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 goingmerry.glb 
Author: Anex (https://sketchfab.com/anex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/one-piece-going-merry-0e1f16189e8b4b4d9d9c3c60893d692b
Title: One Piece -Going Merry
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

export function Goingmerry(props) {
  const { nodes, materials } = useGLTF('/goingmerry.glb')
  return (
    <Float
    speed={2}
    rotationIntensity={2}
    floatIntensity={1}
    floatingRange={[1, 2]}
    position={[0, -2.5, 0]}
  >
    <group {...props} dispose={null} scale={0.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.None} />
      </group>
    </group>
    </Float>
  )
}

useGLTF.preload('/goingmerry.glb')
export default Goingmerry;