/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 meramera.glb 
Author: typhomnt (https://sketchfab.com/typhomnt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/one-piece-mera-mera-no-mi-ac8c016683fb4712ac4c8f6781f4babf
Title: One Piece - Mera Mera no Mi
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Meramera(props) {
  const { nodes, materials } = useGLTF('/meramera.glb')

  
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|_FireFruit_0'].geometry} material={materials.FireFruit} position={[-50.112, -32.301, 0]} rotation={[-Math.PI / 2, 1.363, Math.PI / 2]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|1_FireFruit_0'].geometry} material={materials.FireFruit} position={[15.485, -32.301, -47.659]} rotation={[-0.218, -0.307, -0.067]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|2_FireFruit_0'].geometry} material={materials.FireFruit} position={[40.542, -32.301, 29.455]} rotation={[-2.797, -0.913, -2.865]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|3_FireFruit_0'].geometry} material={materials.FireFruit} position={[-40.542, -32.301, 29.455]} rotation={[-2.797, 0.913, 2.865]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|4_FireFruit_0'].geometry} material={materials.FireFruit} position={[-15.485, -32.301, -47.659]} rotation={[-0.218, 0.307, 0.067]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|5_FireFruit_0'].geometry} material={materials.FireFruit} position={[50.112, -32.301, 0]} rotation={[-Math.PI / 2, -1.363, -Math.PI / 2]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|6_FireFruit_0'].geometry} material={materials.FireFruit} position={[-15.485, -32.301, 47.659]} rotation={[-2.923, 0.307, 3.075]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|7_FireFruit_0'].geometry} material={materials.FireFruit} position={[-40.542, -32.301, -29.455]} rotation={[-0.344, 0.913, 0.277]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|8_FireFruit_0'].geometry} material={materials.FireFruit} position={[40.542, -32.301, -29.455]} rotation={[-0.344, -0.913, -0.277]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|9_FireFruit_0'].geometry} material={materials.FireFruit} position={[15.485, -32.301, 47.659]} rotation={[-2.923, -0.307, -3.075]} scale={32.345} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|10_FireFruit_0'].geometry} material={materials.FireFruit} position={[20.33, -12.883, 29.249]} rotation={[3.024, -0.604, 3.075]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|11_FireFruit_0'].geometry} material={materials.FireFruit} position={[-29.249, -12.883, 20.33]} rotation={[2.974, 0.957, -3.004]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|12_FireFruit_0'].geometry} material={materials.FireFruit} position={[-20.33, -12.883, -29.249]} rotation={[0.117, 0.604, -0.067]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|13_FireFruit_0'].geometry} material={materials.FireFruit} position={[6.307, -12.883, -35.058]} rotation={[0.098, -0.177, 0.017]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|14_FireFruit_0'].geometry} material={materials.FireFruit} position={[35.058, -12.883, 6.307]} rotation={[2.642, -1.369, 2.651]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|15_FireFruit_0'].geometry} material={materials.FireFruit} position={[-6.307, -12.883, 35.058]} rotation={[3.044, 0.177, -3.124]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|16_FireFruit_0'].geometry} material={materials.FireFruit} position={[-35.058, -12.883, -6.307]} rotation={[0.5, 1.369, -0.491]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|17_FireFruit_0'].geometry} material={materials.FireFruit} position={[29.249, -12.883, -20.33]} rotation={[0.168, -0.957, 0.137]} scale={35.36} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|18_FireFruit_0'].geometry} material={materials.FireFruit} position={[35.264, -63.137, 37.25]} rotation={[-2.171, -0.491, -2.538]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|19_FireFruit_0'].geometry} material={materials.FireFruit} position={[-37.25, -63.137, 35.264]} rotation={[-2.145, 0.521, 2.486]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|20_FireFruit_0'].geometry} material={materials.FireFruit} position={[-35.264, -63.137, -37.25]} rotation={[-0.971, 0.491, 0.603]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|21_FireFruit_0'].geometry} material={materials.FireFruit} position={[1.405, -63.137, -51.275]} rotation={[-0.816, -0.019, -0.02]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|22_FireFruit_0'].geometry} material={materials.FireFruit} position={[51.275, -63.137, 1.405]} rotation={[-1.597, -0.755, -1.608]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|23_FireFruit_0'].geometry} material={materials.FireFruit} position={[-1.405, -63.137, 51.275]} rotation={[-2.326, 0.019, 3.122]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|24_FireFruit_0'].geometry} material={materials.FireFruit} position={[-51.275, -63.137, -1.405]} rotation={[-1.545, 0.755, 1.533]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|25_FireFruit_0'].geometry} material={materials.FireFruit} position={[37.25, -63.137, -35.264]} rotation={[-0.996, -0.521, -0.656]} scale={42.416} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|26_FireFruit_0'].geometry} material={materials.FireFruit} position={[18.397, 6.157, 0]} rotation={[Math.PI / 2, -1.13, Math.PI / 2]} scale={23.925} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|27_FireFruit_0'].geometry} material={materials.FireFruit} position={[-9.198, 6.157, 15.932]} rotation={[2.643, 0.469, -2.9]} scale={23.925} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|28_FireFruit_0'].geometry} material={materials.FireFruit} position={[-9.198, 6.157, -15.932]} rotation={[0.498, 0.469, -0.241]} scale={23.925} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|29_FireFruit_0'].geometry} material={materials.FireFruit} position={[9.198, 6.157, -15.932]} rotation={[0.498, -0.469, 0.241]} scale={23.925} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|30_FireFruit_0'].geometry} material={materials.FireFruit} position={[9.198, 6.157, 15.932]} rotation={[2.643, -0.469, 2.9]} scale={23.925} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|31_FireFruit_0'].geometry} material={materials.FireFruit} position={[-18.397, 6.157, 0]} rotation={[Math.PI / 2, 1.13, -Math.PI / 2]} scale={23.925} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|32_FireFruit_0'].geometry} material={materials.FireFruit} position={[45.195, -86.828, 0]} rotation={[-Math.PI / 2, -0.62, -Math.PI / 2]} scale={33.13} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|33_FireFruit_0'].geometry} material={materials.FireFruit} position={[-22.598, -86.828, 39.14]} rotation={[-2.125, 0.295, 2.702]} scale={33.13} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|34_FireFruit_0'].geometry} material={materials.FireFruit} position={[-22.598, -86.828, -39.14]} rotation={[-1.017, 0.295, 0.439]} scale={33.13} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|35_FireFruit_0'].geometry} material={materials.FireFruit} position={[22.598, -86.828, -39.14]} rotation={[-1.017, -0.295, -0.439]} scale={33.13} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|36_FireFruit_0'].geometry} material={materials.FireFruit} position={[22.598, -86.828, 39.14]} rotation={[-2.125, -0.295, -2.702]} scale={33.13} />
        <mesh geometry={nodes['Fruit_Instancer|Fruit_FireLP001|Dupli|37_FireFruit_0'].geometry} material={materials.FireFruit} position={[-45.195, -86.828, 0]} rotation={[-Math.PI / 2, 0.62, Math.PI / 2]} scale={33.13} />
        <mesh geometry={nodes.Fruit_INner_Inner_0.geometry} material={materials.Inner} position={[0, -56.557, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[48.716, 48.716, 55.314]} />
        <mesh geometry={nodes.Fruit_Tp_Fruit_Tip001_0.geometry} material={materials['Fruit_Tip.001']} position={[0, 27.662, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={40.838} />
      </group>
    </group>
  )
}

useGLTF.preload('/meramera.glb')
export default Meramera;